core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("demo.urls")),
    path('admin/', admin.site.urls),
]

demo/urls.py
from django.urls import path

from .views import DemoDetailView, DemoListView, DemoCreateView, DemoDeleteView


app_name = "demo"

urlpatterns = [
    path("", DemoListView.as_view(), name="list"),
    path("detail/<int:pk>", DemoDetailView.as_view(), name="detail"),
    path("create/", DemoCreateView.as_view(), name="create"),
    path("delete/<int:pk>", DemoDeleteView.as_view(), name="delete"),
    
]

demo/models.py
from django.db import models
from django.urls import reverse

class Demo(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.name
    
    def get_absolute_url(self):
        return reverse("demo:list")
    

    

demo/views.py
from django.views.generic import DetailView, ListView, CreateView, DeleteView

from .models import Demo

class DemoDetailView(DetailView):
    model = Demo


class DemoListView(ListView):
    model = Demo


class DemoCreateView(CreateView):
    model = Demo
    fields = ['name', ]

class DemoDeleteView(DeleteView):
    model = Demo
    fields = ['name', ]
    success_url = "/"

templates/demo/demo_confirm_delete.html
<form method="POST" enctype="multipart/form-data">
 
    <!-- Security token -->
    {% csrf_token %}
    <p>Are you sure you want to delete?</p>
     
    <input type="submit" value="Delete">
</form>

templates/demo/demo_detail.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body>
        {{object}}
        <br>
        <a href="{% url 'demo:delete' object.id %}">Delete</a>
    </body>

</html>

templates/demo/demo_form.html
<form method="POST" enctype="multipart/form-data">
 
    <!-- Security token -->
    {% csrf_token %}
 
    <!-- Using the formset -->
    {{ form.as_p }}
     
    <input type="submit" value="Submit">
</form>

templates/demo/demo_list.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <ol>
        {% for object in object_list %}
            <li>
                <a href = "{% url 'demo:detail' object.id %}">
                {{ object }}
                </a>
            </li>
        {% endfor %}
        </ol>
        <a href="{% url 'demo:create' %}">Create</a>
    </body>
</html>